experimenter_name:
  - X, Y
lab: Frank
institution: UCSF
experiment_description: exp
session_description: desc
session_id: d1
subject:
  description: d
  genotype: WT
  sex: M
  species: Rattus norvegicus
  subject_id: a
  date_of_birth: 2023-01-01T00:00:00
  weight: 400
data_acq_device:
  - name: SpikeGadgets
    system: SpikeGadgets
    amplifier: Intan
    adc_circuit: Intan
cameras: []
tasks: []
associated_files: []
associated_video_files: []
times_period_multiplier: 1.5
raw_data_to_volts: 0.195
behavioral_events: []
device:
  name:
    - Trodes
opto_excitation_source: []
optical_fiber: []
virus_injection: []
fs_gui_yamls: []
optogenetic_stimulation_software: ""
electrode_groups:
  - id: 0
    location: CA1
    device_type: tetrode_12.5
    description: g0
    targeted_location: CA1
  - id: 1
    location: CA1
    device_type: tetrode_12.5
    description: g1
    targeted_location: CA1
ntrode_electrode_group_channel_map:
  - ntrode_id: 1
    electrode_group_id: 0
    bad_channels:
      - 1
    map:
      "0": 0
      "1": 1
      "2": 2
      "3": 3
  - ntrode_id: 2
    electrode_group_id: 1
    bad_channels: []
    map:
      "0": 0
      "1": 1
      "2": 2
      "3": 3
