/**
 * @fileoverview Brain-region location suggestion list (split from the legacy `valueList.js`;
 * re-exported by the `valueList` barrel). Used by the electrode-group `location` / `targeted_location`
 * datalists. NOTE: `electrode_group.location` auto-creates Spyglass BrainRegion entries, so keep the
 * casing consistent.
 */

/**
 *  List of body parts/region common across species
 *
 * @returns Body parts/regions of a species
 */
export const locations = () => {
  return [
    ...[
      'Brain (Brain)',
      'White matter (wmt)',
      'Olfactory white matter (olf)',
      'lateral olfactory tract (lot)',
      'corpus callosum and associated subcortical white matter (cc-ec-cing-dwm)',
      'Anterior commissure (ac)',
      'anterior commissure, anterior limb (aca)',
      'anterior commissure, posterior limb (acp)',
      'anterior commissure, intrabulbar part (aci)',
      'Hippocampal white matter (hiw)',
      'alveus of the hippocampus (alv)',
      'ventral hippocampal commissure (vhc)',
      'fornix (f)',
      'fimbria of the hippocampus (fi)',
      'Corticofugal pathways (cfp)',
      'corticofugal tract and corona radiata (ic-cp-lfp-py)',
      'pyramidal decussation (pyx)',
      'Medial lemniscus (ml)',
      'medial lemniscus, unspecified (ml-u)',
      'medial lemniscus decussation (mlx)',
      'Thalamic tracts (tht)',
      'External medullary lamina (eml)',
      'external medullary lamina, unspecified (eml-u)',
      'external medullary lamina, auditory radiation (eml-ar)',
      'internal medullary lamina (iml)',
      'intramedullary thalamic area (ima)',
      'superior cerebellar peduncle and prerubral field (scp-pr)',
      'pretectothalamic lamina (ptl)',
      'mammillotegmental tract (mtg)',
      'commissural stria terminalis (cst)',
      'fasciculus retroflexus (fr)',
      'stria medullaris thalami (sm)',
      'stria terminalis (st)',
      'habenular commissure (hbc)',
      'posterior commissure (pc)',
      'Facial nerve (7n)',
      'facial nerve, unspecified (7n-u)',
      'ascending fibers of the facial nerve (asc7)',
      'genu of the facial nerve (g7)',
      'Optic fiber system and supraoptic decussation (ofs)',
      'optic nerve (2n)',
      'optic tract and optic chiasm (opt-och)',
      'supraoptic decussation (sox)',
      'White matter of the tectum (tew)',
      'commissure of the superior colliculus (csc)',
      'brachium of the superior colliculus (bsc)',
      'inferior colliculus, commissure (cic)',
      'inferior colliculus, brachium (bic)',
      'Cerebellar and precerebellar white matter (cbt)',
      'inferior cerebellar peduncle (icp)',
      'middle cerebellar peduncle (mcp)',
      'transverse fibers of the pons (tfp)',
      'White matter of the brainstem (bsw)',
      'Lateral lemniscus (ll)',
      'lateral lemniscus, commissure (ll-c)',
      'lateral lemniscus, unspecified (ll-u)',
      'acoustic striae (as)',
      'trapezoid body (tz)',
      'spinal trigeminal tract (sp5t)',
      'Gray matter (GM)',
      'Telencephalon (Tel)',
      'Laminated pallium (LamP)',
      'Olfactory bulb (OB)',
      'Glomerular layer of the accessory olfactory bulb (GlA)',
      'Glomerular layer of the olfactory bulb (Gl)',
      'Olfactory bulb, unspecified (OB-u)',
      'Nucleus of the lateral olfactory tract (NLOT)',
      'Cerebral cortex (Cx)',
      'Hippocampal region (HR)',
      'Hippocampal formation (HF)',
      'Fasciola cinereum (FC)',
      'Subiculum (SUB)',
      'Cornu Ammonis (CA)',
      'Cornu ammonis 1 (CA1)',
      'Cornu ammonis 2 (CA2)',
      'Cornu ammonis 3 (CA3)',
      'Dentate gyrus (DG)',
      'Parahippocampal region (PHR)',
      'Postrhinal cortex (POR)',
      'Presubiculum (PrS)',
      'Parasubiculum (PaS)',
      'Perirhinal cortex (PER)',
      'Perirhinal area 35 (PER35)',
      'Perirhinal area 36 (PER36)',
      'Entorhinal cortex (EC)',
      'Medial entorhinal cortex (MEC)',
      'Lateral entorhinal cortex (LEC)',
      'Piriform cortex (PIR)',
      'Piriform cortex, layer 1 (PIR1)',
      'Piriform cortex, layer 2 (PIR2)',
      'Piriform cortex, layer 3 (PIR3)',
      'Cingulate region (CgR)',
      'Cingulate cortex (Cg)',
      'Cingulate area 1 (Cg1)',
      'Cingulate area 2 (Cg2)',
      'Retrosplenial cortex (RS)',
      'Retrosplenial dysgranular area (RSD)',
      'Retrosplenial granular area (RSG)',
      'Insular region (INS)',
      'Agranular insular cortex (AI)',
      'Agranular insular cortex, ventral area (AI-v)',
      'Agranular insular cortex dorsal area  (AI-d)',
      'Agranular insular cortex, posterior area  (AI-p)',
      'Dysgranular insular cortex (DI)',
      'Granular insular cortex (GI)',
      'Frontal region (Front)',
      'Frontal association cortex (FrA)',
      'Orbitofrontal cortex (Orb)',
      'Medial orbital area (MO)',
      'Ventral orbital area (VO)',
      'Ventrolateral orbital area (VLO)',
      'Lateral orbital area (LO)',
      'Dorsolateral orbital area (DLO)',
      'Mediofrontal cortex (MFC)',
      'Prelimbic area (PrL)',
      'Infralimbic area (IL)',
      'Motor cortex (M)',
      'Primary motor area (M1)',
      'Secondary motor area (M2)',
      'Frontal association area 3 (Fr3)',
      'Parietal region (Par)',
      'Somatosensory cortex (SS)',
      'Primary somatosensory area (S1)',
      'Primary somatosensory area, face representation (S1-f)',
      'Primary somatosensory area, barrel field (S1-bf)',
      'Primary somatosensory area, dysgranular zone (S1-dz)',
      'Primary somatosensory area, forelimb representation (S1-fl)',
      'Primary somatosensory area, hindlimb representation (S1-hl)',
      'Primary somatosensory area, trunk representation (S1-tr)',
      'Secondary somatosensory area (S2)',
      'Posterior parietal cortex (PPC)',
      'Parietal association cortex, medial area (mPPC)',
      'Parietal association cortex, lateral area (lPPC)',
      'Parietal association cortex, posterior area  (PtP)',
      'Occipital region (Oc)',
      'Visual cortex (Vis)',
      'Primary visual area (V1)',
      'Secondary visual area (V2)',
      'Secondary visual area, medial part (V2M)',
      'Secondary visual area, lateral part (V2L)',
      'Temporal region (Te)',
      'Temporal association cortex (TeA)',
      'Auditory cortex (Au)',
      'Primary auditory area (Au1)',
      'Secondary auditory area (Au2)',
      'Secondary auditory area, dorsal part (Au2-d)',
      'Secondary auditory area, ventral part (Au2-v)',
      'Non-laminated pallium (N-LamP)',
      'Claustrum (CLA)',
      'Endopiriform nucleus (Endo)',
      'Amygdaloid area, unspecified (Am-u)',
      ' Subpallium (SubPAL)',
      'Striatum (Str)',
      'Caudate putamen (CPu)',
      'Nucleus accumbens (NAc)',
      'Nucleus accumbens, core (NAc-c)',
      'Nucleus accumbens, shell (NAc-sh)',
      'Ventral striatal region, unspecified (VSR-u)',
      'Pallidum (PAL)',
      'Globus pallidus external (GPe)',
      'Globus pallidus external, medial part (GPe-m)',
      'Globus pallidus external, lateral part (GPe-l)',
      'Entopeduncular nucleus (EP)',
      'Ventral pallidum (VP)',
      'Basal forebrain region  (BRF)',
      'Basal forebrain region, unspecified (BFR-u)',
      'Bed nucleus of the stria terminalis (BNST)',
      'Septal region (Sep)',
      'Subthalamic nucleus (STh)',
      'Diencephalon (Dien)',
      'Prethalamus (Thal-Pre)',
      'Reticular (pre)thalamic nucleus (RT)',
      'Reticular (pre)thalamic nucleus, unspecified (RT-u)',
      'Reticular (pre)thalamic nucleus, auditory segment (RT-a)',
      'Zona incerta (ZI)',
      'Zona incerta, dorsal part (ZI-d)',
      'Zona incerta, ventral part (ZI-v)',
      'Zona incerta, rostral part (ZI-r)',
      'Zona incerta, caudal part (ZI-c)',
      'Zona incerta, A13 dopamine cells (ZI-A13)',
      'Zona incerta, A11 dopamine cells (ZI-A11)',
      'Fields of Forel (FoF)',
      'Pregeniculate nucleus (PrG)',
      'Subgeniculate nucleus (SubG)',
      'Intergeniculate leaflet (IGL)',
      'Epithalamus (Thal-EPI)',
      'Lateral habenular nucleus (LHb)',
      'Medial habenular nucleus (MHb)',
      'Nucleus of the stria medullaris (SMn)',
      'Pineal gland (PG)',
      'Dorsal thalamus (Thal-D)',
      'Anterior nuclei of the dorsal thalamus (ANT)',
      'Anterodorsal thalamic nucleus (AD)',
      'Anteroventral thalamic nucleus (AV)',
      'Anteroventral thalamic nucleus, dorsomedial part (AV-dm)',
      'Anteroventral thalamic nucleus, ventrolateral part (AV-vl)',
      'Anteromedial thalamic nucleus (AM)',
      'Interanteromedial thalamic nucleus (IAM)',
      'Paraventricular thalamic nuclei (anterior and posterior) (PV)',
      'Intermediodorsal thalamic nucleus (IMD)',
      'Parataenial thalamic nucleus (PT)',
      'Subparafascicular nucleus (SPF)',
      'Posterior intralaminar nucleus (PIL)',
      'Ventral midline group of the dorsal thalamus (V-MID)',
      'Rhomboid thalamic nucleus (Rh)',
      'Reuniens thalamic nucleus (Re)',
      'Retroreuniens thalamic nucleus (RRe)',
      'Xiphoid thalamic nucleus (Xi)',
      'Mediodorsal nucleus of the dorsal thalamus (MD)',
      'Mediodorsal thalamic nucleus, lateral part (MD-l)',
      'Mediodorsal thalamic nucleus, central part (MD-c)',
      'Mediodorsal thalamic nucleus, medial part (MD-m)',
      'Ventral nuclei of the dorsal thalamus (VENT)',
      'Ventral anterior thalamic nucleus (VA)',
      'Ventromedial thalamic nucleus (VM)',
      'Ventrolateral thalamic nucleus (VL)',
      'Angular thalamic nucleus (Ang)',
      'Ventral posterior thalamic nucleus (VPN)',
      'Ventral posteromedial thalamic nucleus (VPM)',
      'Ventral posterolateral thalamic nucleus (VPL)',
      'Ventral posterior nucleus of the thalamus, parvicellular part (VP-pc)',
      'Submedius thalamic nucleus (SMT)',
      'Intralaminar nuclei of the dorsal thalamus (ILM)',
      'Paracentral thalamic nucleus (PCN)',
      'Central medial thalamic nucleus (CM)',
      'Central lateral thalamic nucleus (CL)',
      'Parafascicular thalamic nucleus (PF)',
      'Ethmoid-Limitans nucleus (Eth)',
      'Posterior complex of the dorsal thalamus (PoC)',
      'Posterior thalamic nucleus (Po)',
      'Posterior thalamic nuclear group, triangular part (Po-t)',
      'Lateral posterior (pulvinar) complex of the dorsal thalamus (LP)',
      'Lateral posterior thalamic nucleus, mediorostral part (LP-mr)',
      'Lateral posterior thalamic nucleus, mediocaudal part (LP-mc)',
      'Lateral posterior thalamic nucleus, lateral part (LP-l)',
      'Laterodorsal thalamic nuclei of the dorsal thalamus (LD)',
      'Laterodorsal thalamic nucleus, dorsomedial part (LD-dm)',
      'Laterodorsal thalamic nucleus, ventrolateral part (LD-vl)',
      'Dorsal lateral geniculate nucleus (DLG)',
      'Medial geniculate complex of the dorsal thalamus (MG)',
      'Medial geniculate body, ventral division (MG-v)',
      'Medial geniculate body, dorsal division (MG-d)',
      'Medial geniculate body, marginal zone (MG-mz)',
      'Medial geniculate body, medial division (MG-m)',
      'Medial geniculate body, suprageniculate nucleus (MG-sg)',
      'Hypothalamus (HY)',
      'Hypothalamic region, unspecified (HTh-u)',
      'Pretectum (PreT)',
      'Pretectal region (PRT)',
      'Nucleus sagulum (Sag)',
      'Mesencephalon (Mes)',
      'Midbrain (MB)',
      'Tectum (Tc)',
      'Inferior colliculus (IC)',
      'Inferior colliculus, dorsal cortex (DCIC)',
      'Inferior colliculus, central nucleus (CNIC)',
      'Inferior colliculus, external cortex (ECIC)',
      'Superior colliculus (Su)',
      'Superficial gray layer of the superior colliculus (SuG)',
      'Deeper layers of the superior colliculus (SuD)',
      'Tegmentum (Tg)',
      'Substantia nigra (SN)',
      'Substantia nigra, reticular part (SN-r)',
      'Substantia nigra, compact part (SN-c)',
      'Substantia nigra, lateral part (SN-l)',
      'Ventral tegmental area (VTA)',
      'Peripeduncular nucleus (PP)',
      'Interpeduncular nucleus (IP)',
      'Periaqueductal gray (PAG)',
      'Brainstem, unspecified (BS-u)',
      'Rhombencephalon (Rho)',
      'Metencephalon (Met)',
      'Pontine nuclei (Pn)',
      'Cerebellum (Cb)',
      'Molecular cell layer of the cerebellum (Cb-m)',
      'Cerebellum, unspecified (Cb-u)',
      'Myelencephalon (Myel)',
      'Cochlear nucleus, ventral part (VCN)',
      'Ventral cochlear nucleus, anterior part (AVCN)',
      'Ventral cochlear nucleus, posterior part (PVCN)',
      'Ventral cochlear nucleus, cap area (Cap)',
      'Ventral cochlear nucleus, granule cell layer (GCL)',
      'Cochlear nucleus, dorsal part (DCN)',
      'Dorsal cochlear nucleus, molecular layer (DCNM)',
      'Dorsal cochlear nucleus, fusiform and granule layer (DCNFG)',
      'Dorsal cochlear nucleus, deep core (DCND)',
      'Spinal trigeminal nucleus (Sp5n)',
      'Periventricular gray (PVG)',
      'Superior olivary complex (SO)',
      'Nucleus of the trapezoid body (NTB)',
      'Superior paraolivary nucleus (SPN)',
      'Medial superior olive (MSO)',
      'Lateral superior olive (LSO)',
      'Superior periolivary region (SPR)',
      'Ventral periolivary nuclei (VPO)',
      'Nuclei of the lateral lemniscus (NLL)',
      'Lateral lemniscus, ventral nucleus (VLL)',
      'Lateral lemniscus, intermediate nucleus (ILL)',
      'Lateral lemniscus, dorsal nucleus (DLL)',
      'Inferior olive (IO)',
      'Ventricular system (V)',
      'ventricular system, unspecified (V-u)',
      '4th ventricle (4V)',
      'central canal (CC)',
      'spinal cord (SpC)',
      'Inner ear (IE)',
      'vestibular apparatus (VeA)',
      'cochlea (Co)',
      'cochlear nerve (8cn)',
      'vestibular nerve (8vn)',
      'spiral ganglion (SpG)',
    ],
  ];
};
