/**
 * @fileoverview Subject + lab controlled-vocabulary suggestion lists (split from the legacy
 * `valueList.js`; re-exported by the `valueList` barrel). Gender acronyms/full names, the lab /
 * institution list, genotypes, and the DANDI species (Latin binomial) list.
 */

/**
 * List of genders
 *
 * @returns Genders
 */
export const genderAcronym = () => {
  return [...['M', 'F', 'U', 'O']];
};

/**
 * Full meaning of acronym
 *
 * @returns  Provides the full meaning of gender
 */
export const genders = () => {
  return [...['Male', 'Female', 'Unspecified', '0ther']];
};

/**
 * List of labs
 *
 * @returns Labs
 */
export const labs = () => {
  return [
    ...[
      'Air Force Institute of Technology Graduate School of Engineering & Management',
      'Albert Einstein College of Medicine',
      'American University',
      'Arizona State University Campus Immersion',
      'Arizona State University Digital Immersion',
      'Arkansas State University',
      'Augusta University',
      'Auburn University',
      'Azusa Pacific University',
      'Ball State University',
      'Baylor College of Medicine',
      'Baylor University',
      'Binghamton University',
      'Boise State University',
      'Boston College',
      'Boston University',
      'Bowling Green State University',
      'Brandeis University',
      'Brigham Young University',
      'Brown University',
      'California Institute of Technology',
      'California State University, East Bay',
      'California State University, Fresno',
      'California State University, Fullerton',
      'California State University, Long Beach',
      'California State University, San Bernardino',
      'Carnegie Mellon University',
      'Case Western Reserve University',
      'Catholic University of America',
      'Central Michigan University',
      'Chapman University',
      'Claremont Graduate University',
      'Clark Atlanta University',
      'Clark University',
      'Clarkson University',
      'Clemson University',
      'Cleveland State University',
      'College of William and Mary',
      'Colorado School of Mines',
      'Colorado State University',
      'Columbia University',
      'Cornell University',
      'Creighton University',
      'CUNY City College',
      'Dartmouth College',
      'DePaul University',
      'Drexel University',
      'Duke University',
      'Duquesne University',
      'East Carolina University',
      'East Tennessee State University',
      'Eastern Michigan University',
      'Eastern Virginia Medical School',
      'Emory University',
      'Florida Agricultural and Mechanical University',
      'Florida Atlantic University',
      'Florida Institute of Technology',
      'Florida International University',
      'Florida State University',
      'Fordham University',
      'George Mason University',
      'George Washington University',
      'Georgetown University',
      'Georgia Institute of Technology',
      'Georgia Southern University',
      'Georgia State University',
      'Graduate Center, CUNY',
      'Harvard University',
      'Howard University',
      'Icahn School of Medicine at Mount Sinai',
      'Idaho State University',
      'Illinois Institute of Technology',
      'Illinois State University',
      'Indiana University – Purdue University Indianapolis',
      'Indiana University Bloomington',
      'Indiana University of Pennsylvania',
      'Iowa State University',
      'Jackson State University',
      'James Madison University',
      'Johns Hopkins University',
      'Kansas State University',
      'Kennesaw State University',
      'Kent State University',
      'Lehigh University',
      'Loma Linda University',
      'Long Island University',
      'Louisiana State University',
      'Louisiana Tech University',
      'Loyola Marymount University',
      'Loyola University Chicago',
      'Marquette University',
      'Marshall University',
      'Massachusetts Institute of Technology',
      'Mayo Clinic College of Medicine and Science',
      'Medical College of Wisconsin',
      'Medical University of South Carolina',
      'Mercer University',
      'Miami University',
      'Michigan State University',
      'Michigan Technological University',
      'Middle Tennessee State University',
      'Mississippi State University',
      'Missouri University of Science and Technology',
      'Montana State University',
      'Montclair State University',
      'Morgan State University',
      'New Jersey Institute of Technology',
      'New Mexico State University',
      'New York University',
      'North Carolina A & T State University',
      'North Carolina State University',
      'North Dakota State University',
      'Northeastern University',
      'Northern Arizona University',
      'Northern Illinois University',
      'Northwestern University',
      'Nova Southeastern University',
      'Oakland University',
      'Ohio State University',
      'Ohio University',
      'Oklahoma State University–Stillwater',
      'Old Dominion University',
      'Oregon Health & Science University',
      'Oregon State University',
      'Pennsylvania State University',
      'Portland State University',
      'Prairie View A&M University',
      'Princeton University',
      'Purdue University',
      'Rensselaer Polytechnic Institute',
      'Rice University',
      'Rochester Institute of Technology',
      'Rockefeller University',
      'Rowan University',
      'Rutgers University–Camden',
      'Rutgers University–New Brunswick',
      'Rutgers University–Newark',
      'Saint Louis University',
      'Sam Houston State University',
      'San Diego State University',
      'San Francisco State University',
      'Seton Hall University',
      'South Dakota State University',
      'Southern Illinois University Carbondale',
      'Southern Methodist University',
      'Southern University',
      'Stanford University',
      'Stevens Institute of Technology',
      'Stony Brook University',
      'SUNY College of Environmental Science and Forestry',
      'Syracuse University',
      'Tarleton State University',
      'Teachers College at Columbia University',
      'Temple University',
      'Tennessee State University',
      'Tennessee Technological University',
      'Texas A&M University',
      'Texas A&M University–Corpus Christi',
      'Texas A&M University–Kingsville',
      'Texas Christian University',
      'Texas Southern University',
      'Texas State University',
      'Texas Tech University',
      'Texas Tech University Health Sciences Center',
      'The New School',
      'Thomas Jefferson University',
      'Tufts University',
      'Tulane University',
      'Uniformed Services University of the Health Sciences',
      'University at Albany, SUNY',
      'University at Buffalo',
      'University of Akron Main Campus',
      'University of Alabama',
      'University of Alabama at Birmingham',
      'University of Alabama in Huntsville',
      'University of Alaska Fairbanks',
      'University of Arizona',
      'University of Arkansas',
      'University of Arkansas at Little Rock',
      'University of Arkansas for Medical Sciences',
      'University of California, Berkeley',
      'University of California, Davis',
      'University of California, Irvine',
      'University of California, Los Angeles',
      'University of California, Merced',
      'University of California, Riverside',
      'University of California, San Diego',
      'University of California, San Francisco',
      'University of California, Santa Barbara',
      'University of California, Santa Cruz',
      'University of Central Florida',
      'University of Chicago',
      'University of Cincinnati',
      'University of Colorado Boulder',
      'University of Colorado Colorado Springs',
      'University of Colorado Denver',
      'University of Connecticut',
      'University of Dayton',
      'University of Delaware',
      'University of Denver',
      'University of Florida',
      'University of Georgia',
      'University of Hawaii at Manoa',
      'University of Houston',
      'University of Idaho',
      'University of Illinois Chicago',
      'University of Illinois Urbana-Champaign',
      'University of Iowa',
      'University of Kansas',
      'University of Kentucky',
      'University of Louisiana at Lafayette',
      'University of Louisville',
      'University of Maine',
      'University of Maryland, Baltimore',
      'University of Maryland, Baltimore County',
      'University of Maryland, College Park',
      'University of Maryland, Eastern Shore',
      'University of Massachusetts Amherst',
      'University of Massachusetts Boston',
      'University of Massachusetts Chan Medical School',
      'University of Massachusetts Dartmouth',
      'University of Massachusetts Lowell',
      'University of Memphis',
      'University of Miami',
      'University of Michigan',
      'University of Minnesota',
      'University of Mississippi',
      'University of Missouri',
      'University of Missouri–Kansas City',
      'University of Missouri–St. Louis',
      'University of Montana',
      'University of Nebraska at Omaha',
      'University of Nebraska Medical Center',
      'University of Nebraska–Lincoln',
      'University of Nevada, Las Vegas',
      'University of Nevada, Reno',
      'University of New England',
      'University of New Hampshire',
      'University of New Mexico',
      'University of New Orleans',
      'University of North Carolina at Chapel Hill',
      'University of North Carolina at Charlotte',
      'University of North Carolina at Greensboro',
      'University of North Carolina Wilmington',
      'University of North Dakota',
      'University of North Florida',
      'University of North Texas',
      'University of Notre Dame',
      'University of Oklahoma',
      'University of Oklahoma Health Sciences Center',
      'University of Oregon',
      'University of Pennsylvania',
      'University of Pittsburgh',
      'University of Puerto Rico at Río Piedras',
      'University of Rhode Island',
      'University of Rochester',
      'University of San Diego',
      'University of South Alabama',
      'University of South Carolina',
      'University of South Dakota',
      'University of South Florida',
      'University of Southern California',
      'University of Southern Mississippi',
      'University of Tennessee',
      'University of Tennessee Health Science Center',
      'University of Texas at Arlington',
      'University of Texas at Austin',
      'University of Texas at Dallas',
      'University of Texas at El Paso',
      'University of Texas at San Antonio',
      'University of Texas Health Science Center at Houston',
      'University of Texas Health Science Center at San Antonio',
      'University of Texas Medical Branch',
      'University of Texas Southwestern Medical Center',
      'University of Toledo',
      'University of Tulsa',
      'University of Utah',
      'University of Vermont',
      'University of Virginia',
      'University of Washington',
      'University of Wisconsin–Madison',
      'University of Wisconsin–Milwaukee',
      'University of Wyoming',
      'Utah State University',
      'Vanderbilt University',
      'Villanova University',
      'Virginia Commonwealth University',
      'Virginia Tech',
      'Wake Forest University',
      'Washington State University',
      'Washington University in St. Louis',
      'Wayne State University',
      'Weill Cornell Medicine',
      'West Chester University of Pennsylvania',
      'West Virginia University',
      'Western Michigan University',
      'Wichita State University',
      'Worcester Polytechnic Institute',
      'Wright State University',
      'Yale University',
    ],
  ];
};

export const genotypes = () => {
  return [
    ...[
      'ApoE',
      'SCN2A',
      'Wild Type',
    ],
  ];
};

/**
 * List of species
 *
 * @returns Species
 */
export const species = () => {
  // from Charles River
  return [
    ...[
        'Callithrix jacchus',
        'Danio rerio',
        'Drosophila melanogaster',
        'Fringilla coelebs',
        'Macaca mulatta',
        'Mesocricetus auratus',
        'Mus musculus',
        'Oryctolagus cuniculus',
        'Rattus norvegicus',
        'Sus scrofa',
    ],
  ];
};
